import manifest from './frames.json';
import { FRAME_COUNT } from './phase';

/** One bundled NASA SVS frame and its provenance. Generated by scripts/frames/select-and-fetch.mjs. */
export interface MoonFrame {
  /** 0..59 — position in the phase sequence, phase ≈ index / 60. */
  index: number;
  /** Same-origin path under /frames/. */
  file: string;
  /** suncalc phase at the frame's UTC hour: 0 = new, 0.5 = full. */
  phase: number;
  /** UTC hour the frame depicts. */
  utc: string;
  /** NASA SVS hour-of-year frame number (1 = Jan 1 00:00 UTC). */
  sourceFrame: number;
  /** Dial-a-Moon illuminated percentage for that hour — provenance cross-check. */
  nasaIlluminationPct: number;
  /** suncalc illuminated percentage for that hour. */
  suncalcIlluminationPct: number;
}

export interface FrameManifest {
  credit: string;
  source: string;
  license: string;
  generated: string;
  frameSize: number;
  frames: MoonFrame[];
}

/** The committed manifest, validated once at load. */
export function loadFrames(): readonly MoonFrame[] {
  const { frames } = manifest as FrameManifest;
  if (frames.length !== FRAME_COUNT) {
    throw new Error(`frame manifest has ${frames.length} entries, expected ${FRAME_COUNT}`);
  }
  return frames;
}

export const FRAME_CREDIT: string = (manifest as FrameManifest).credit;
